version: "3.5"

services:
  # api01: &api
  #   # TODO: use docker hub
  #   build:
  #     dockerfile: Dockerfile
  #   hostname: api01
  #   environment:
  #     - DB_HOSTNAME=db

  #   # Não é necessário expor qualquer porta além da porta do load balancer,
  #   # mas é comum as pessoas o fazerem para testarem suas APIs e conectarem
  #   # ao banco de dados na fase de desenvolvimento.
  #   ports:
  #     - "8081:8080"
  #   depends_on:
  #     - db
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.6"
  #         memory: "200MB"

  # api02:
    # <<: *api
    # hostname: api02
    # environment:
    #   - DB_HOSTNAME=db
    # ports:
    #   - "8082:8080"

  # nginx:
      # image: nginx:latest
      # volumes:
      #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # depends_on:
      #   - api01
      #   - api02
      # ports:
      #     # Obrigatório expor/usar a porta 9999 no load balancer!
      #   - "9999:9999"
      # deploy:
      #   resources:
      #     limits:
      #       cpus: "0.17"
      #       memory: "10MB"

  db:
    hostname: db
    restart: always
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.13"
    #       memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-2024q1-go
